// import Scheduler from "../src/scheduler/Scheduler";
// import {SchedRoom, SchedSection, TimeSlot} from "../src/scheduler/IScheduler";
// import {assert, expect} from "chai";
//
//
// describe("Scheduler tests", function () {
//
//     let scheduler: Scheduler;
//     let sectionsTest2: SchedSection[] = [
//         {
//             courses_dept: "cpsc",
//             courses_id: "340",
//             courses_uuid: "1319",
//             courses_pass: 101,
//             courses_fail: 7,
//             courses_audit: 2
//         },
//         {
//             courses_dept: "cpsc",
//             courses_id: "340",
//             courses_uuid: "3397",
//             courses_pass: 171,
//             courses_fail: 3,
//             courses_audit: 1
//         },
//         {
//             courses_dept: "cpsc",
//             courses_id: "344",
//             courses_uuid: "62413",
//             courses_pass: 93,
//             courses_fail: 2,
//             courses_audit: 0
//         },
//         {
//             courses_dept: "cpsc",
//             courses_id: "344",
//             courses_uuid: "72385",
//             courses_pass: 43,
//             courses_fail: 1,
//             courses_audit: 0
//         }
//     ];
//     let roomsTest2: SchedRoom[] = [
//         {
//             rooms_shortname: "AERL",
//             rooms_number: "120",
//             rooms_seats: 144,
//             rooms_lat: 49.26372,
//             rooms_lon: -123.25099
//         },
//         {
//             rooms_shortname: "ALRD",
//             rooms_number: "105",
//             rooms_seats: 94,
//             rooms_lat: 49.2699,
//             rooms_lon: -123.25318
//         },
//         {
//             rooms_shortname: "ANGU",
//             rooms_number: "098",
//             rooms_seats: 260,
//             rooms_lat: 49.26486,
//             rooms_lon: -123.25364
//         },
//         {
//             rooms_shortname: "BUCH",
//             rooms_number: "A101",
//             rooms_seats: 275,
//             rooms_lat: 49.26826,
//             rooms_lon: -123.25468
//         }
//     ];
//
//     let expectedTest2: Array<[SchedRoom, SchedSection, TimeSlot]> = [
//         [
//             {
//                 rooms_lat: 49.26826,
//                 rooms_lon: -123.25468,
//                 rooms_number: "A101",
//                 rooms_seats: 275,
//                 rooms_shortname: "BUCH"
//             },
//             {
//                 courses_audit: 1,
//                 courses_dept: "cpsc",
//                 courses_fail: 3,
//                 courses_id: "340",
//                 courses_pass: 171,
//                 courses_uuid: "3397",
//             },
//             "MWF 0800-0900"
//         ],
//         [
//             {
//                 rooms_lat: 49.26826,
//                 rooms_lon: -123.25468,
//                 rooms_number: "A101",
//                 rooms_seats: 275,
//                 rooms_shortname: "BUCH",
//             },
//             {
//                 courses_audit: 2,
//                 courses_dept: "cpsc",
//                 courses_fail: 7,
//                 courses_id: "340",
//                 courses_pass: 101,
//                 courses_uuid: "1319",
//             },
//             "MWF 0900-1000"
//         ], [
//             {
//                 rooms_lat: 49.26826,
//                 rooms_lon: -123.25468,
//                 rooms_number: "A101",
//                 rooms_seats: 275,
//                 rooms_shortname: "BUCH",
//             },
//             {
//                 courses_audit: 0,
//                 courses_dept: "cpsc",
//                 courses_fail: 2, courses_id: "344",
//                 courses_pass: 93,
//                 courses_uuid: "62413",
//             },
//             "MWF 1000-1100"
//         ],
//         [
//             {
//                 rooms_lat: 49.26826,
//                 rooms_lon: -123.25468,
//                 rooms_number: "A101",
//                 rooms_seats: 275,
//                 rooms_shortname: "BUCH",
//             },
//             {
//                 courses_audit: 0,
//                 courses_dept: "cpsc",
//                 courses_fail: 1,
//                 courses_id: "344",
//                 courses_pass: 43,
//                 courses_uuid: "72385",
//             },
//             "MWF 1100-1200"
//         ]];
//
//     let sectionsTest3: SchedSection[] = [{
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "1385",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "1386",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "crwr",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "46406",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "crwr",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "46407",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "crwr",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "75158",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "mtrl",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "2676",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "obst",
//         courses_id: "549",
//         courses_avg: 95,
//         courses_uuid: "98843",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "bmeg",
//         courses_id: "597",
//         courses_avg: 95,
//         courses_uuid: "43501",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "bmeg",
//         courses_id: "597",
//         courses_avg: 95,
//         courses_uuid: "43502",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "crwr",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "26257",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "crwr",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "92881",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "crwr",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "71171",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "crwr",
//         courses_id: "599",
//         courses_avg: 95,
//         courses_uuid: "81354",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "econ",
//         courses_id: "516",
//         courses_avg: 95,
//         courses_uuid: "10016",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 2
//     }, {
//         courses_dept: "econ",
//         courses_id: "516",
//         courses_avg: 95,
//         courses_uuid: "10017",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 2
//     }, {
//         courses_dept: "cnps",
//         courses_id: "535",
//         courses_avg: 95,
//         courses_uuid: "28349",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 1
//     }, {
//         courses_dept: "cnps",
//         courses_id: "535",
//         courses_avg: 95,
//         courses_uuid: "28350",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 1
//     }, {
//         courses_dept: "kin",
//         courses_id: "500",
//         courses_avg: 95,
//         courses_uuid: "86831",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "19490",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "19491",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "93963",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "93964",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "sowk",
//         courses_id: "570",
//         courses_avg: 95,
//         courses_uuid: "88881",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "kin",
//         courses_id: "499",
//         courses_avg: 95,
//         courses_uuid: "72706",
//         courses_pass: 5,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "math",
//         courses_id: "532",
//         courses_avg: 95,
//         courses_uuid: "29971",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "math",
//         courses_id: "532",
//         courses_avg: 95,
//         courses_uuid: "29972",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "mtrl",
//         courses_id: "564",
//         courses_avg: 95,
//         courses_uuid: "49773",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "mtrl",
//         courses_id: "564",
//         courses_avg: 95,
//         courses_uuid: "49774",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "rhsc",
//         courses_id: "501",
//         courses_avg: 95,
//         courses_uuid: "10582",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 4
//     }, {
//         courses_dept: "epse",
//         courses_id: "606",
//         courses_avg: 95,
//         courses_uuid: "76362",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "kin",
//         courses_id: "500",
//         courses_avg: 95,
//         courses_uuid: "59530",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "28877",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "28878",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "psyc",
//         courses_id: "501",
//         courses_avg: 95,
//         courses_uuid: "94900",
//         courses_pass: 8,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "psyc",
//         courses_id: "501",
//         courses_avg: 95,
//         courses_uuid: "94901",
//         courses_pass: 8,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "epse",
//         courses_id: "682",
//         courses_avg: 95,
//         courses_uuid: "86974",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 9
//     }, {
//         courses_dept: "epse",
//         courses_id: "682",
//         courses_avg: 95,
//         courses_uuid: "86975",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 9
//     }, {
//         courses_dept: "nurs",
//         courses_id: "424",
//         courses_avg: 95,
//         courses_uuid: "96195",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "nurs",
//         courses_id: "424",
//         courses_avg: 95,
//         courses_uuid: "96196",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "412",
//         courses_avg: 90.18,
//         courses_uuid: "78875",
//         courses_pass: 11,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.5,
//         courses_uuid: "79479",
//         courses_pass: 18,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.33,
//         courses_uuid: "85074",
//         courses_pass: 18,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.33,
//         courses_uuid: "85075",
//         courses_pass: 18,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "edcp",
//         courses_id: "473",
//         courses_avg: 95,
//         courses_uuid: "16690",
//         courses_pass: 19,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "edcp",
//         courses_id: "473",
//         courses_avg: 95,
//         courses_uuid: "16691",
//         courses_pass: 19,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.48,
//         courses_uuid: "46423",
//         courses_pass: 23,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.72,
//         courses_uuid: "91932",
//         courses_pass: 25,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 92.54,
//         courses_uuid: "68540",
//         courses_pass: 26,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 96.11,
//         courses_uuid: "68539",
//         courses_pass: 27,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.29,
//         courses_uuid: "19187",
//         courses_pass: 28,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.17,
//         courses_uuid: "75628",
//         courses_pass: 29,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "412",
//         courses_avg: 90.16,
//         courses_uuid: "68557",
//         courses_pass: 31,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 93.33,
//         courses_uuid: "19182",
//         courses_pass: 33,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 90.82,
//         courses_uuid: "68543",
//         courses_pass: 33,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.85,
//         courses_uuid: "46425",
//         courses_pass: 34,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 90.02,
//         courses_uuid: "19184",
//         courses_pass: 62,
//         courses_fail: 0,
//         courses_audit: 0
//     }];
//
//     let sectionsTest4: SchedSection[] = [{
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "1385",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "1386",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "46406",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "46407",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "75158",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "2676",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "98843",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "43501",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "43502",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "26257",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "92881",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "71171",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "81354",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "10016",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 2
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "10017",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 2
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "28349",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 1
//     }];
//
//     let sectionsTest5: SchedSection[] = [{
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "1385",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "1386",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "46406",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "46407",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "75158",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "2676",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "98843",
//         courses_pass: 1,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "43501",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "43502",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "26257",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "92881",
//         courses_pass: 2,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "71171",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "81354",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "10016",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 2
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "10017",
//         courses_pass: 3,
//         courses_fail: 0,
//         courses_audit: 2
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "28349",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 1
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "28350",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 1
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "86831",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "19490",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "19491",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "cpsc",
//         courses_id: "589",
//         courses_avg: 95,
//         courses_uuid: "93963",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "93964",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "sowk",
//         courses_id: "570",
//         courses_avg: 95,
//         courses_uuid: "88881",
//         courses_pass: 4,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "kin",
//         courses_id: "499",
//         courses_avg: 95,
//         courses_uuid: "72706",
//         courses_pass: 5,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "math",
//         courses_id: "532",
//         courses_avg: 95,
//         courses_uuid: "29971",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "math",
//         courses_id: "532",
//         courses_avg: 95,
//         courses_uuid: "29972",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "mtrl",
//         courses_id: "564",
//         courses_avg: 95,
//         courses_uuid: "49773",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "mtrl",
//         courses_id: "564",
//         courses_avg: 95,
//         courses_uuid: "49774",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "rhsc",
//         courses_id: "501",
//         courses_avg: 95,
//         courses_uuid: "10582",
//         courses_pass: 6,
//         courses_fail: 0,
//         courses_audit: 4
//     }, {
//         courses_dept: "epse",
//         courses_id: "606",
//         courses_avg: 95,
//         courses_uuid: "76362",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "kin",
//         courses_id: "500",
//         courses_avg: 95,
//         courses_uuid: "59530",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "28877",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "musc",
//         courses_id: "553",
//         courses_avg: 95,
//         courses_uuid: "28878",
//         courses_pass: 7,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "psyc",
//         courses_id: "501",
//         courses_avg: 95,
//         courses_uuid: "94900",
//         courses_pass: 8,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "psyc",
//         courses_id: "501",
//         courses_avg: 95,
//         courses_uuid: "94901",
//         courses_pass: 8,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "epse",
//         courses_id: "682",
//         courses_avg: 95,
//         courses_uuid: "86974",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 9
//     }, {
//         courses_dept: "epse",
//         courses_id: "682",
//         courses_avg: 95,
//         courses_uuid: "86975",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 9
//     }, {
//         courses_dept: "nurs",
//         courses_id: "424",
//         courses_avg: 95,
//         courses_uuid: "96195",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "nurs",
//         courses_id: "424",
//         courses_avg: 95,
//         courses_uuid: "96196",
//         courses_pass: 9,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "412",
//         courses_avg: 90.18,
//         courses_uuid: "78875",
//         courses_pass: 11,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.5,
//         courses_uuid: "79479",
//         courses_pass: 18,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.33,
//         courses_uuid: "85074",
//         courses_pass: 18,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.33,
//         courses_uuid: "85075",
//         courses_pass: 18,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "edcp",
//         courses_id: "473",
//         courses_avg: 95,
//         courses_uuid: "16690",
//         courses_pass: 19,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "edcp",
//         courses_id: "473",
//         courses_avg: 95,
//         courses_uuid: "16691",
//         courses_pass: 19,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.48,
//         courses_uuid: "46423",
//         courses_pass: 23,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.72,
//         courses_uuid: "91932",
//         courses_pass: 25,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 92.54,
//         courses_uuid: "68540",
//         courses_pass: 26,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 96.11,
//         courses_uuid: "68539",
//         courses_pass: 27,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 91.29,
//         courses_uuid: "19187",
//         courses_pass: 28,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.17,
//         courses_uuid: "75628",
//         courses_pass: 29,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "412",
//         courses_avg: 90.16,
//         courses_uuid: "68557",
//         courses_pass: 31,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 93.33,
//         courses_uuid: "19182",
//         courses_pass: 33,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 90.82,
//         courses_uuid: "68543",
//         courses_pass: 33,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "330",
//         courses_avg: 90.85,
//         courses_uuid: "46425",
//         courses_pass: 34,
//         courses_fail: 0,
//         courses_audit: 0
//     }, {
//         courses_dept: "adhe",
//         courses_id: "329",
//         courses_avg: 90.02,
//         courses_uuid: "19184",
//         courses_pass: 62,
//         courses_fail: 0,
//         courses_audit: 0
//     }];
//     let roomsTest6: SchedRoom[] = [{
//             rooms_shortname: "LSK",
//             rooms_number: "200",
//             rooms_seats: 205,
//             rooms_lat: 49.26545,
//             rooms_lon: -123.25533
//         }, {
//             rooms_shortname: "PHRM",
//             rooms_number: "1101",
//             rooms_seats: 236,
//             rooms_lat: 49.26229,
//             rooms_lon: -123.24342
//         }, {
//             rooms_shortname: "ANGU",
//             rooms_number: "098",
//             rooms_seats: 260,
//             rooms_lat: 49.26486,
//             rooms_lon: -123.25364
//         }, {
//             rooms_shortname: "SRC",
//             rooms_number: "220A",
//             rooms_seats: 299,
//             rooms_lat: 49.2683,
//             rooms_lon: -123.24894
//         }, {
//             rooms_shortname: "SRC",
//             rooms_number: "220B",
//             rooms_seats: 299,
//             rooms_lat: 49.2683,
//             rooms_lon: -123.24894
//         }, {
//             rooms_shortname: "SRC",
//             rooms_number: "220C",
//             rooms_seats: 299,
//             rooms_lat: 49.2683,
//             rooms_lon: -123.24894
//         }, {
//             rooms_shortname: "LSC",
//             rooms_number: "1001",
//             rooms_seats: 350,
//             rooms_lat: 49.26236,
//             rooms_lon: -123.24494
//         }, {
//             rooms_shortname: "LSC",
//             rooms_number: "1002",
//             rooms_seats: 350,
//             rooms_lat: 49.26236,
//             rooms_lon: -123.24494
//         }, {
//             rooms_shortname: "HEBB",
//             rooms_number: "100",
//             rooms_seats: 375,
//             rooms_lat: 49.2661,
//             rooms_lon: -123.25165
//         }, {
//             rooms_shortname: "OSBO",
//             rooms_number: "A",
//             rooms_seats: 442,
//             rooms_lat: 49.26047,
//             rooms_lon: -123.24467
//         }];
//     let expectedTest3: Array<[SchedRoom, SchedSection, TimeSlot]>;
//
//     before(function () {
//         //
//     });
//
//     beforeEach(function () {
//         scheduler = new Scheduler();
//     });
//
//     after(function () {
//         //
//     });
//
//     afterEach(function () {
//         //
//     });
//
//     it("should return the only section in the only room in a timeslot", function () {
//         let sections: SchedSection[] = [{
//             courses_dept: "a",
//             courses_id: "b",
//             courses_uuid: "c",
//             courses_pass: 1,
//             courses_fail: 1,
//             courses_audit: 1,
//         }];
//         let rooms: SchedRoom[] = [{
//             rooms_shortname: "roomname",
//             rooms_number: "123A",
//             rooms_seats: 30,
//             rooms_lat: 30.404955,
//             rooms_lon: 39.303945,
//         }];
//         let expected: Array<[SchedRoom, SchedSection, TimeSlot]> = [];
//         expected.push([rooms[0], sections[0], "MWF 0800-0900"]);
//
//         expect(scheduler.schedule(sections, rooms)).to.deep.equal(expected);
//     });
//
//     it("only section doesn't fit in the only room, should return empty array", function () {
//         let sections: SchedSection[] = [{
//             courses_dept: "a",
//             courses_id: "b",
//             courses_uuid: "c",
//             courses_pass: 30,
//             courses_fail: 1,
//             courses_audit: 1,
//         }];
//         let rooms: SchedRoom[] = [{
//             rooms_shortname: "roomname",
//             rooms_number: "123A",
//             rooms_seats: 30,
//             rooms_lat: 30.404955,
//             rooms_lon: 39.303945,
//         }];
//         let expected: Array<[SchedRoom, SchedSection, TimeSlot]> = [];
//
//         expect(scheduler.schedule(sections, rooms)).to.deep.equal(expected);
//     });
//
//     it("surplus of rooms < 15 sections, should return all sections" +
//         " in sequential timeslots in the first room", function () {
//         expect(scheduler.schedule(sectionsTest2, roomsTest2)).to.deep.equal(expectedTest2);
//     });
//
//     it("surplus of rooms > 15 sections, should return all sections " +
//         "in sequential timeslots in best 2 roms", () => {
//         expect(scheduler.schedule(sectionsTest3, roomsTest6).length).to.equal(56);
//     });
//
//     it("enough sections to need all rooms but not fill them all, " +
//         "should return all sections in sequential timeslots, last timeslots for smallest room empty", function () {
//         expect(scheduler.schedule(sectionsTest3, roomsTest2).length).to.equal(56);
//     });
//
//     it("more sections than rooms, should place only the largest sections in timeslots ", () => {
//         roomsTest2.splice(2);
//         expect(scheduler.schedule(sectionsTest3, roomsTest2).length).to.equal(30);
//     });
//
//     it("16 sections of the same course, should only schedule 15 of them", () => {
//         expect(scheduler.schedule(sectionsTest4, roomsTest2).length).to.equal(15);
//     });
//
//     it("more complicated 16 sections of the same course, should only be able to schedule 15 of them", () => {
//         expect(scheduler.schedule(sectionsTest5, roomsTest2).length).to.equal(50);
//     });
//
//
// });
